#!/usr/bin/python3
from socket import socket, AF_INET, SOCK_STREAM
import sys

s = socket(AF_INET, SOCK_STREAM)
host = '192.168.0.23'
port = 1500

s.connect((host, port))
for line in sys.stdin:
    s.send(line.encode('ascii'))
s.close()
